### ISSUE TITLE
šumniki

### ISSUE THREAD

**Issue by janrudof** [janrudof/APPR-2017-18#2]
Eno vprašanje glede zamenjave besed s šumniki: pri tabela5 sem želel z gsub zamenjati niz "Prenočitve (v 1000)" v "Prenocitve (v 1000)", zato da kasneje ne bi imel problemov s šumniki, vendar ne deluje.
Kako to popravim?

**Comment by jaanos** [comment]
Problem s trenutnim pristopom je ta, da so oklepaji v regularnih izrazih posebni znaki - če hočeš ujeti natanko oklepaje, je treba prednje postaviti `\` (podvojen, ker je že `\` poseben znak v R-jevih nizih):
```R
tabela5$VRSTA_MERITVE <- gsub("Preno.itve \\(v 1000\\)", "Prenocitve \\(v 1000\\)", tabela5$VRSTA_MERITVE)
```
Lahko bi sicer oklepaje nadomestil tudi s pikami, kot si že naredil s šumniki.

Sicer pa ni nič narobe, če imaš šumnike v vsebini razpredelnic - svetoval bi celo, da jih ohraniš, saj se bodo te oznake lahko pojavljale na grafih (npr. v legendi).
