### ISSUE TITLE
Barvna paleta za zemljevid & razdelitev tabelc

### ISSUE THREAD

**Issue by janrudof** [janrudof/APPR-2017-18#3]
Pri vizualizaciji sem naletel na težavo, da nikakor ne morem narediti nove legende za obarvanje držav, glede na število obiskovalcev. Poleg tega sem v uvozu želel tabelo 3 radeliti na dve (povpečno število, celotno število) pa nevem zakaj ne dela. Moje mnenje je, da zaradi šumnikov v tabeli, vendar jih z gsub nemorem zamenjati oz. ne dela.

**Comment by jaanos** [comment]
V razpredelnici `potovanja.2016` se vsaka država za izbrano leto pojavi večkrat - enkrat za vsako kratico. Verjetno želiš prikazati skupno število potovanj za vsako državo - treba bo torej grupirati po državah:
```R
graf.potovanja.2016 <- ggplot() + aes(x = long, y = lat, group = group,
                                      fill = STEVILO_POTOVANJ / 1000000) +
  geom_polygon(data = potovanja.2016 %>% group_by(DRZAVA_POTOVANJA) %>%
                 summarise(STEVILO_POTOVANJ = sum(STEVILO_POTOVANJ)) %>%
                 right_join(zemljevid.tabela, by = c("DRZAVA_POTOVANJA" = "NAME_LONG")), color = "black") +
  guides(fill = guide_colorbar(title = "STEVILO POTOVANJ\n(v milijonih)"))
```
Deljenje z 1000000 je potrebno, da se v legendi ne prikaže eksponentna notacija števil.

Pri tem zemljevidu je sicer problem, da sta podatka za Italijo in Hrvaško neprimerljivo večja kot za vse ostale države, ki so potem na zemljevidu podobne barve. Ena možnost bi bila, da se ti dve nariše posebej (torej da se ju izloči iz podatkov, potem pa se doda še en `geom_polygon`, ki ročno določi barve za ti dve državi - glej HovnikK15#1 za primer).

Druga možnost, ki bi tukaj bila (glede na razpon vrednosti) morda bolj primerna, je ta, da prikažeš barve na logaritemski lestvici. V tem primeru se bo nekoliko težje znebiti eksponentne notacije - najlažje bo šlo z uporabo knjižnice `scales`:
```R
library(scales)
point <- format_format(big.mark = ".", decimal.mark = ",", scientific = FALSE)
graf.potovanja.2016 <- ggplot() + aes(x = long, y = lat, group = group,
                                      fill = STEVILO_POTOVANJ) +
  geom_polygon(data = potovanja.2016 %>% group_by(DRZAVA_POTOVANJA) %>%
                 summarise(STEVILO_POTOVANJ = sum(STEVILO_POTOVANJ)) %>%
                 right_join(zemljevid.tabela, by = c("DRZAVA_POTOVANJA" = "NAME_LONG")), color = "black") +
  guides(fill = guide_colorbar(title = "STEVILO POTOVANJ")) +
  scale_fill_gradient(trans = "log", breaks = 10^seq(0, 6, 2), labels = point)
```

Še to: v tvojih podatkih vsa imena držav ne ustrezajo tistim v zemljevidu. Predlagam, da si z `unique(tabela5$DRZAVA_POTOVANJA)` pogledaš imena v svojih podatkih, potem pa lahko z
```R
unique(tabela5$DRZAVA_POTOVANJA) %in% zemljevid.tabela$NAME_LONG
```
preveriš, katera se dejansko pojavijo v zemljevidu, in ostala spremeniš tako, da bodo ustrezala. Seznam imen držav iz zemljevida dobiš z `levels(zemljevid.tabela$NAME_LONG)`.
