### ISSUE TITLE
Warning sporočila

### ISSUE THREAD

**Issue by janrudof** [janrudof/APPR-2017-18#6]
Pri uvozu se mi vedno napišejo ta obvestila npr. tabela2: Warning: 15 parsing failures.
row # A tibble: 5 x 5 col     row col   expected  actual    file                       expected   <int> <chr> <chr>     <chr>     <chr>                      actual 1     1 NA    4 columns 1 columns 'podatki/NETO_DOHODEK.csv' file 2     2 NA    4 columns 2 columns 'podatki/NETO_DOHODEK.csv' row 3    47 NA    4 columns 2 columns 'podatki/NETO_DOHODEK.csv' col 4    92 NA    4 columns 1 columns 'podatki/NETO_DOHODEK.csv' expected 5    93 NA    4 columns 2 columns 'podatki/NETO_DOHODEK.csv'
... ........................... ... ............................................................ ........ ........................................................................................................................................................... ...... .............. [... truncated]
Warning: 2 parsing failures.
row # A tibble: 2 x 4 col     row   col expected actual expected   <int> <int> <chr>    <chr>  actual 1    72    NA a number N      row 2    84    NA a number N     

Warning messages:
1: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)
2: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)

Zanima me, kako se jih znebim? vse dela sicer normalno, ampak pri prevajanju sporočila se mi še vedno pojavljajo.

**Comment by jaanos** [comment]
Da se ti opozorila ne izpisujejo v poročilo, v glavo blokov kode, kjer se pojavijo, dodaj parameter `warning = FALSE`. V konzolo se bodo še vedno izpisovala - vzrok je ta, da datoteke CSV nimajo v vseh vrsticah istega števila celic.

**Comment by janrudof** [comment]
Sem popravil. Hvala.

**Comment by jaanos** [comment]
V redu, zdaj ti poročilo prevede, tako da bom dodal povezavo do trenutnega commita na repoztorij za zagovore. Če boš še kaj spreminjal in boš želel posodobiti povezavo, odpri issue na [repozitoriju za zagovore](https://github.com/jaanos/APPR-zagovori) (glej navodila spodaj).

Še to: opažam, da si v `libraries.r` nadomestil knjižnico `reshape2` z `reshape`. Če nimaš dobrega razloga za to, svetujem, da raje uporabiš `reshape2`, saj zna knjižnica `reshape` povzročati težave pri uporabi nekaterih funkcij iz knjižnice `dplyr` (npr. `rename`).
