### ISSUE TITLE
Številke shiny

### ISSUE THREAD

**Issue by janrudof** [janrudof/APPR-2017-18#8]
Pri izdelavi shiny programa za zemljevide, sem naletel na težavo. Pri sliderInput sem navedel letnice (od 2006 do 2016), vendar mi jih (ko poženem program) izpiše z decimalno vejico. Kako to popravim?

Lp

**Comment by jaanos** [comment]
Da se znebiš vejice (ta je uporabljena kot ločilo tisočic), lahko pri funkciji `sliderInput` dodaš parameter `sep = ""`.
